services:
  # Backend API
  - type: web
    name: hrms-backend
    runtime: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    region: singapore
    envVars:
      - key: APP_NAME
        value: HRMS
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "4000"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MYSQL_ATTR_SSL_CA
        value: /etc/ssl/certs/ca-certificates.crt
      - key: SANCTUM_STATEFUL_DOMAINS
        sync: false
      - key: SESSION_DRIVER
        value: cookie
      - key: LOG_CHANNEL
        value: stderr
      - key: CACHE_DRIVER
        value: redis
      - key: QUEUE_CONNECTION
        value: redis
      - key: REDIS_CLIENT
        value: phpredis
      - key: REDIS_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_DB
        value: "0"
      - key: REDIS_CACHE_DB
        value: "1"
      - key: REDIS_QUEUE
        value: default


